name: Pipeline-Backend
on:
#   push:
#     branches:
#       - master
#     tags:
#       - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag for backend docker image"
        required: true
  push:
    tags:
      - '*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build Backend Docker image
        run: |
          cd backend
          docker build -t nacromancer858/backend-image:${{ github.event.inputs.tag }} .
        working-directory: ./backend
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     
      - name: Push Backend Docker image
        run: docker push nacromancer858/backend-image:${{ github.event.inputs.tag }}
        working-directory: ./backend
       
      - name: Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${secrets.USER_NAME}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
          cd /home/ubuntu/
          docker rmi -f backend_container
          docker pull nacromancer858/backend-image:${{ github.event.inputs.tag }}
          docker run -d -p 3333:3333 --name backend_container nacromancer858/backend-image:${{ github.event.inputs.tag }}

          '
