name: Pipeline-Backend
on:
  push:
    branches:
    - master

    tags:
    - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Tag
      id: set_tag
      run: "fullTag=${{ github.ref }}\ntag=${fullTag#refs/tags/}\necho \"tag=${tag}\" >> $GITHUB_OUTPUT \n#magic___^_^___line\n"

    - name: Build Frontend Docker image
      run: docker build -t nacromancer858/backend-image:${{ steps.set_tag.outputs.tag }} .
      working-directory: ./backend

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Frontend Docker image
      run: docker push nacromancer858/backend-image:${{ steps.set_tag.outputs.tag }}
      working-directory: ./backend

    - name: Deploy to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo chmod 666 /var/run/docker.sock
          sudo docker stop $(docker ps -q)
          sudo docker rm $(sudo docker ps -aq)
          sudo docker pull nacromancer858/backend-image:${{ steps.set_tag.outputs.tag }}
          sudo docker run -d -p 80:80 --name backend_container nacromancer858/backend-image:${{ steps.set_tag.outputs.tag }}
